server:
  port: 3000

logging:
  level:
    com:
      iteratec:
        evoting:
          storageservice: ${LOG_LVL:INFO}

spring:
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        default_schema: ${DEFAULT_SCHEMA:storage}
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql:${DB_URL://localhost:6543}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
    hikari: # https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      connectionTimeout: 60000 # Default 30000
      minimum-idle: 1
      maximum-pool-size: 10
      max-lifetime: 30000
      idle-timeout: 10000 # 10000ms is the minimum allowed
  flyway:
    url: jdbc:postgresql:${DB_URL://localhost:6543}/${DB_NAME:postgres}
    schemas: ${DEFAULT_SCHEMA:storage}
    user: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  sql:
    init:
      platform: postgres

web3:
  mnemonic: ${WEB3_MNEMONIC:}
  derivationPathIndex: ${WEB3_DERIVATION_PATH_INDEX:8}
  environment: ${WEB3_ENVIRONMENT:local}
  network: ${WEB3_NETWORK:local} #This loads a default config of known networks at the time this was built. The following settings can override the default network config or replace it altogether
  ensRegistry: ${WEB3_ENS_REGISTRY:}
  httpRpcServer: ${WEB3_HTTP_RPC_SERVER:}
  wsRpcServer: ${WEB3_WS_RPC_SERVER:}

assetFile: ""
assetArgument1: ""
assetArgument2: ""


