server:
  port: 8080
  url: ${ORACLE_URL:http://localhost:8080}
  private_key: ${PRIVATE_KEY:}

keycloak:
  realm: realm-name
  resource: resource-name
  auth-server-url: ${KEY_CLOAK_URL:http://localhost:8180/auth}
  ssl-required: external
  cors: true
  credentials:
    secret: ${KEY_CLOAK_SECRET:}
  principal-attribute: preferred_username

logging:
  level:
    com:
      iteratec:
        evoting:
          oracle:
            service: ${LOG_LVL:DEBUG}

Member:
  reimport: ${REIMPORT_MEMBER:false}
  registerAdministrator: ${REGISTER_ADMINISTRATOR:true}

synchronization:
  rate: ${SYNC_RATE:600000} #Sync every 10 Minutes if keycloak is enabled

spring:
  application:
    name: decentraVote-oracle
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        default_schema: ${DEFAULT_SCHEMA:oracle}
    hibernate:
      ddl-auto: update

  datasource:
    platform: postgres
    url: jdbc:postgresql:${DB_URL://localhost:6543}/${DB_NAME:postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS ${DEFAULT_SCHEMA:oracle};

web3:
  mnemonic: ${WEB3_MNEMONIC:}
  rpcServer: ${WEB3_RPC_SERVER:HTTP://127.0.0.1:7545}
  derivationPathIndex: ${WEB3_DERIVATION_PATH_INDEX:9}
  environment: ${WEB3_ENVIRONMENT:local}
  network: ${WEB3_NETWORK:local} #This loads a default config of known networks at the time this was built. The following settings can override the default network config or replace it altogether
  ensRegistry: ${WEB3_ENS_REGISTRY:}
  httpRpcServer: ${WEB3_HTTP_RPC_SERVER:}
  wsRpcServer: ${WEB3_WS_RPC_SERVER:}


storageService:
  enabled: ${STORAGE_ENABLED:true}
  url: ${SS_URL:http://localhost:3000}
